Repository S-nect1/matchday-server, pull requests merged in 2025-04, with the labels that each got.

#22 Refactor: #17-match
  src/main/java/com/example/moim/club/dto/ClubInput.java
  src/main/java/com/example/moim/global/entity/AgeRange.java
  src/main/java/com/example/moim/global/entity/EventType.java
  src/main/java/com/example/moim/global/entity/Gender.java
  src/main/java/com/example/moim/global/exception/ResponseCode.java
  src/main/java/com/example/moim/match/controller/MatchController.java
  src/main/java/com/example/moim/match/dto/ConfirmedMatchOutput.java
  src/main/java/com/example/moim/match/dto/MatchClubSearchCond.java
  src/main/java/com/example/moim/match/dto/MatchInput.java
  src/main/java/com/example/moim/match/dto/MatchSearchCond.java
  src/main/java/com/example/moim/match/dto/MatchSearchOutput.java
  src/main/java/com/example/moim/match/dto/RegisteredMatchDto.java
  src/main/java/com/example/moim/match/entity/Gender.java
  src/main/java/com/example/moim/match/entity/Match.java
  src/main/java/com/example/moim/match/entity/MatchSize.java
  src/main/java/com/example/moim/match/entity/MatchUser.java
  src/main/java/com/example/moim/match/repository/MatchRepositoryImpl.java
  src/main/java/com/example/moim/match/service/MatchAggregateService.java
  src/main/java/com/example/moim/match/service/MatchService.java
  src/test/java/com/example/moim/match/MatchAggregateServiceTest.java
  src/test/java/com/example/moim/match/MatchServiceTest.java
Labels: :recycle: refactor

#28 Feat(#23): 매치 취소 구현
  src/main/java/com/example/moim/club/entity/UserClub.java
  src/main/java/com/example/moim/global/exception/ResponseCode.java
  src/main/java/com/example/moim/match/controller/MatchController.java
  src/main/java/com/example/moim/match/entity/Match.java
  src/main/java/com/example/moim/match/service/MatchService.java
  src/main/java/com/example/moim/notification/dto/MatchCancelClubEvent.java
  src/main/java/com/example/moim/notification/dto/MatchCancelUserEvent.java
  src/main/java/com/example/moim/notification/entity/Notifications.java
  src/main/java/com/example/moim/notification/service/NotificationEventHandler.java
Labels: :sparkles: feature

#27 ✨ refactor(#26): FileStore -> FileService 로 리팩터링
  .gitignore
  build.gradle
  deploy/local.init.sql
  src/main/java/com/example/moim/club/dto/request/ClubImgInput.java
  src/main/java/com/example/moim/club/service/ClubCommandServiceImpl.java
  src/main/java/com/example/moim/global/util/FileStore.java
  src/main/java/com/example/moim/global/util/file/config/AwsS3Config.java
  src/main/java/com/example/moim/global/util/file/config/LocalFileConfig.java
  src/main/java/com/example/moim/global/util/file/exception/FileValidator.java
  src/main/java/com/example/moim/global/util/file/exception/ValidFile.java
  src/main/java/com/example/moim/global/util/file/exception/advice/AwsS3ControllerAdvice.java
  src/main/java/com/example/moim/global/util/file/exception/advice/LocalFileControllerAdvice.java
  src/main/java/com/example/moim/global/util/file/model/AwsS3.java
  src/main/java/com/example/moim/global/util/file/service/AwsS3FileService.java
  src/main/java/com/example/moim/global/util/file/service/FileService.java
  src/main/java/com/example/moim/global/util/file/service/LocalFileService.java
  src/main/java/com/example/moim/global/util/uuid/SystemUuidHolder.java
  src/main/java/com/example/moim/global/util/uuid/UuidHolder.java
  src/main/java/com/example/moim/user/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/example/moim/club/service/ClubCommandServiceImplTest.java
  src/test/java/com/example/moim/global/util/file/service/LocalFileServiceTest.java
Labels: :sparkles: feature, :recycle: refactor

#32 ✨ refactor: Notice 도메인 리팩터링(공지 추가/공지 조회)
  deploy/local.init.sql
  src/main/java/com/example/moim/club/controller/NoticeController.java
  src/main/java/com/example/moim/club/controller/NoticeControllerDocs.java
  src/main/java/com/example/moim/club/dto/request/NoticeInput.java
  src/main/java/com/example/moim/club/dto/response/NoticeOutput.java
  src/main/java/com/example/moim/club/repository/ClubRepositoryImpl.java
  src/main/java/com/example/moim/club/repository/NoticeRepository.java
  src/main/java/com/example/moim/club/repository/NoticeRepositoryCustom.java
  src/main/java/com/example/moim/club/repository/NoticeRepositoryImpl.java
  src/main/java/com/example/moim/club/service/ClubCommandServiceImpl.java
  src/main/java/com/example/moim/club/service/NoticeCommandService.java
  src/main/java/com/example/moim/club/service/NoticeCommandServiceImpl.java
  src/main/java/com/example/moim/club/service/NoticeQueryService.java
  src/main/java/com/example/moim/club/service/NoticeQueryServiceImpl.java
  src/main/java/com/example/moim/config/security/SecurityConfig.java
  src/test/java/com/example/moim/club/service/NoticeCommandServiceImplTest.java
  src/test/java/com/example/moim/club/service/NoticeQueryServiceImplTest.java
Labels: :recycle: refactor
